blog/urls.py
from . import views
from django.conf.urls import url

app_name = "blog"

urlpatterns = [
    url(r'^$', views.blog, name='blog'),
    url(r'^blogtopics/$', views.blogtopics, name='blogtopics'),
    url(r'^blogtopics/(?P<blogtopic_id>\d+)/$', views.blogtopic, name='blogtopic'),
    url(r'^new_blogentry/(?P<blogtopic_id>\d+)/$', views.new_blogentry, name='new_blogentry'),
    url(r'^edit_blogentry/(?P<blogentry_id>\d+)/$', views.edit_blogentry, name='edit_blogentry'),
    url(r'^blogentry/(?P<blogentry_id>\d+)/$', views.blogentry, name='blogentry'),
    url(r'^blogentry/(?P<blogentry_id>\d+)/add_to_fav/$', views.add_to_fav, name='add_to_fav'),
    url(r'^blogentry/(?P<blogentry_id>\d+)/remove_from_fav/$', views.remove_from_fav, name='remove_from_fav'),
    url(r'edit_blogcomment/(?P<blogentry_id>\d+)/(?P<blogcomment_id>\d+)/$', views.edit_blogcomment,
        name='edit_blogcomment'),
    url(r'^blogfavourites/$', views.blogfavourites, name='blogfavourites'),
    url(r'^delete_blogentry/(?P<blogtopic_id>\d+)/(?P<blogentry_id>\d+)/$', views.delete_blogentry,
        name='delete_blogentry'),
    url(r'^alluserentries/(?P<user_id>\d+)/$', views.alluserentries, name='alluserentries'),
    url(r'^myentries/(?P<user_id>\d+)/$', views.myentries, name='myentries'),
]

learning_log/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('learning_logs.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^notes/', include('notes.urls', namespace='notes')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User


# создание модели раздела Blogtopic с указанием названия раздела, датой добавления и изображением раздела
class Blogtopic(models.Model):
    blogtext = models.CharField(max_length=200)
    blogdate_added = models.DateTimeField(auto_now_add=True)
    blogtopicimage = models.ImageField(upload_to='images', default='images/defaultimage.png', blank=True, null=True)

    def __str__(self):
        return self.blogtext

class Blogresttype(models.Model):
    blogtext = models.CharField(max_length=50)
    blogtopicimage = models.ImageField(upload_to='images', default='images/defaultimage.png', blank=True, null=True)

    def __str__(self):
        return self.blogtext
# создание модели статей Blogentry с указанием привязанного к статье раздела, автора статьи, названия статьи,
# текста статьи, даты добавления статьи, атрибута like (ответственного за добавление в избранное) и привязанного
# к статье изображения
class Blogentry(models.Model):
    blogtopic = models.ForeignKey(Blogtopic, on_delete=models.CASCADE)
    blogentryowner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blogentryowner')
    blogresttypes = models.ForeignKey(Blogresttype, on_delete=models.CASCADE, blank=True, null=True)
    blogtitle = models.CharField(max_length=150)
    blogtext = models.TextField()
    blogdate_added = models.DateTimeField(auto_now_add=True)
    bloglike = models.ManyToManyField(User, blank=True)
    blogentryimage = models.ImageField(upload_to='images', default='images/defaultimage.png', blank=True, null=True)

    # возвращает представление текста как 'текст'+'...', если длина статьи составляет более 50 знаков
    def __str__(self):
        # возвращает строковое представление модели
        if len(self.blogtext) > 50:
            return self.blogtext[:50] + '...'
        else:
            return self.blogtext


# создание модели комментариев Blogcomment с указанием привязанной к комментарию статьи, привязанного автора
# комментария, текста комментария, даты добавления комментария, даты обновления комментария, активного состояния комментария
class Blogcomment(models.Model):
    blogpost = models.ForeignKey(Blogentry, on_delete=models.CASCADE, related_name='blogcomments')
    blogname = models.ForeignKey(User, on_delete=models.CASCADE)
    blogbody = models.TextField()
    blogcreated = models.DateTimeField(auto_now_add=True)
    blogupdated = models.DateTimeField(auto_now=True)
    blogactive = models.BooleanField(default=True)

blog/forms.py
from django import forms
from .models import Blogtopic, Blogentry, Blogcomment, Blogresttype


# форма для модели Blogtopic с указанием полей и их обозначениями
class BlogtopicForm(forms.ModelForm):
    class Meta:
        model = Blogtopic
        fields = ['blogtext', 'blogtopicimage']
        labels = {'blogtext': 'Название раздела', 'blogtopicimage': 'Загрузите изображение'}


# форма для модели Blogentry с указанием полей и их обозначениями
class BlogentryForm(forms.ModelForm):
    class Meta:
        model = Blogentry
        fields = ['blogtitle', 'blogtext', 'blogentryimage', 'blogtopic', 'blogresttypes']
        labels = {'blogtitle': 'Название статьи', 'blogtext': 'Текст статьи', 'blogentryimage': 'Загрузите изображение', 'blogtopic':'Выберите континент', 'blogresttypes':'Тип отдыха'}
        widgets = {'blogtext': forms.Textarea(attrs={'cols': 80})}


# форма для модели Blogcomment с указанием полей и их обозначениями
class BlogcommentForm(forms.ModelForm):
    class Meta:
        model = Blogcomment
        fields = ['blogbody']
        labels = {'blogbody': ''}

blog/views.py
from logging import NullHandler
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Blogtopic, Blogentry, Blogcomment
from .forms import BlogentryForm, BlogcommentForm


# функция представления всех разделов на странице
def blog(request):
    blogtop = Blogentry.objects.order_by('-blogdate_added')
    read_more = '...продолжить читать статью'
    for blogentry in blogtop:
        blogtopic = blogentry.blogtopic
        blockid = blogtopic.id
        if len(blogentry.blogtext) > 50:
            blogentry.blogtext = f"{blogentry.blogtext[:50]}"
        if len(blogentry.blogtitle) > 50:
            blogentry.blogtitle = f"{blogentry.blogtitle[:50]}..."
    context = {'blogtop': blogtop, 'read_more': read_more, 'blogtopic': blogtopic, 'id': blockid}
    return render(request, 'blog/blogindex.html', context)


@login_required
def blogtopics(request):
    blogtopics = Blogtopic.objects.order_by('blogdate_added')
    context = {'blogtopics': blogtopics}
    return render(request, 'blog/blogtopics.html', context)


# функция представления всех статей раздела на странице
@login_required
def blogtopic(request, blogtopic_id):
    blogtopic = Blogtopic.objects.get(id=blogtopic_id)
    read_more = '...продолжить читать статью'
    blogentries = blogtopic.blogentry_set.order_by('-blogdate_added')
    for blogentry in blogentries:
        if len(blogentry.blogtext) > 50:
            blogentry.blogtext = blogentry.blogtext[:50]
    context = {'blogtopic': blogtopic, 'blogentries': blogentries, 'read_more': read_more}
    return render(request, 'blog/blogtopic.html', context)


# функция добавления новой статьи в раздел
@login_required
def new_blogentry(request, blogtopic_id):
    blogtopic = Blogtopic.objects.get(id=blogtopic_id)
    if request.method != 'POST':
        form = BlogentryForm()
    else:
        form = BlogentryForm(request.POST, request.FILES)
        if form.is_valid():
            new_blogentry = form.save(commit=False)
            new_blogentry.blogtopic = blogtopic
            new_blogentry.blogentryowner = request.user
            new_blogentry.save()
            return HttpResponseRedirect(reverse('blog:blog'))
    context = {'blogtopic': blogtopic, 'form': form}
    return render(request, 'blog/new_blogentry.html', context)


# функция изменения статьи
@login_required
def edit_blogentry(request, blogentry_id):
    blogentry = Blogentry.objects.get(id=blogentry_id)
    blogtopic = blogentry.blogtopic
    if blogentry.blogentryowner != request.user:
        return render(request, 'learning_logs/notyours.html')
    if request.method != 'POST':
        form = BlogentryForm(instance=blogentry)
    else:
        form = BlogentryForm(instance=blogentry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blog:blogentry', args=[blogentry.id]))
    context = {'blogentry': blogentry, 'blogtopic': blogtopic, 'form': form}
    return render(request, 'blog/edit_blogentry.html', context)


# функция представления страницы статьи
@login_required
def blogentry(request, blogentry_id):
    blogentry = Blogentry.objects.get(id=blogentry_id)
    blogtopic = blogentry.blogtopic
    if request.user not in blogentry.bloglike.all():
        end = 'needtoadd'
    else:
        end = 'Данная статья уже добавлена в избранное'
    all_comments = Blogcomment.objects.filter(blogpost=blogentry).order_by('blogcreated')
    if request.method != 'POST':
        form = BlogcommentForm()
    else:
        form = BlogcommentForm(data=request.POST)
        if form.is_valid():
            blogcomment = form.save(commit=False)
            blogcomment.blogpost = blogentry
            blogcomment.blogname = request.user
            blogcomment.save()
            return HttpResponseRedirect(reverse('blog:blogentry', args=[blogentry_id]))

    context = {'blogentry': blogentry, 'blogtopic': blogtopic, 'form': form, 'all_comments': all_comments, 'end': end}
    return render(request, 'blog/blogentry.html', context)


# функция удаления статьи
def delete_blogentry(request, blogtopic_id, blogentry_id):
    blogentry = Blogentry.objects.get(id=blogentry_id)
    if blogentry.blogentryowner != request.user:
        return render(request, 'learning_logs/notyours.html')
    else:
        blogentry = Blogentry.objects.filter(id=blogentry_id)
        blogentry.delete()
    return HttpResponseRedirect(reverse('blog:blog'))


# функция добавления статьи в избранное
@login_required
def add_to_fav(request, blogentry_id):
    blogentry = Blogentry.objects.get(id=blogentry_id)
    if request.user not in blogentry.bloglike.all():
        blogentry.bloglike.add(request.user)
        end = 'needtoadd'
    else:
        end = 'Данная статья уже добавлена в избранное'
    return HttpResponseRedirect(reverse('blog:blogentry', args=[blogentry_id]))


# функция удаления статьи из избранного
@login_required
def remove_from_fav(request, blogentry_id):
    blogentry = Blogentry.objects.get(id=blogentry_id)
    if request.user in blogentry.bloglike.all():
        blogentry.bloglike.remove(request.user)
        end = ''
    else:
        end = 'Данная статья уже удалена из избранного'
    return HttpResponseRedirect(reverse('blog:blogfavourites'))


# функция представления страницы избранного
@login_required
def blogfavourites(request):
    blogfavourites = Blogentry.objects.filter(bloglike=request.user)
    read_more = '...продолжить читать статью'
    for fav in blogfavourites:
        if len(fav.blogtext) > 50:
            fav.blogtext = fav.blogtext[:50]
    context = {'blogfavourites': blogfavourites, 'read_more': read_more}
    return render(request, 'blog/blogfavourites.html', context)


# функция изменения комментария
@login_required
def edit_blogcomment(request, blogentry_id, blogcomment_id):
    blogcomment = Blogcomment.objects.get(id=blogcomment_id)
    blogentry = blogcomment.blogpost

    # all_comments = Comment.objects.filter(post=entry)
    # for comment in all_comments:
    if blogcomment.blogname != request.user:
        raise Http404
    else:
        if request.method != 'POST':
            form = BlogcommentForm(instance=blogcomment)
        else:
            form = BlogcommentForm(instance=blogcomment, data=request.POST)
            if form.is_valid():
                blogcomment.save()
                return HttpResponseRedirect(reverse('blog:blogentry', args=[blogentry_id]))
    context = {'blogcomment': blogcomment, 'blogentry': blogentry, 'form': form}
    return render(request, 'blog/edit_blogcomment.html', context)


# функция представления страницы всех статей определенного пользователя
@login_required
def alluserentries(request, user_id):
    alluserentries = Blogentry.objects.filter(blogentryowner=user_id).order_by('-blogdate_added')
    read_more = '...продолжить читать статью'
    for blogentry in alluserentries:
        blogtopic = blogentry.blogtopic
        id = blogtopic.id
        if len(blogentry.blogtext) > 50:
            blogentry.blogtext = blogentry.blogtext[:50]
    context = {'alluserentries': alluserentries, 'read_more': read_more, 'blogentry': blogentry, 'blogtopic': blogtopic,
               'id': id}
    return render(request, 'blog/alluserentries.html', context)


@login_required
def myentries(request, user_id):
    myentries = Blogentry.objects.filter(blogentryowner=user_id).order_by('-blogdate_added')
    read_more = '...продолжить читать статью'
    context = {'myentries': myentries, 'read_more': read_more}
    for blogentry in myentries:
        if blogentry.blogtext is not None:
            blogtopic = blogentry.blogtopic
            id = blogtopic.id
            context = {'myentries': myentries, 'read_more': read_more, 'blogentry': blogentry, 'blogtopic': blogtopic,
                       'id': id}
        if len(blogentry.blogtext) > 50:
            blogentry.blogtext = blogentry.blogtext[:50]

    return render(request, 'blog/myentries.html', context)

blog/templates/blog/alluserentries.html
{% extends "learning_logs/base.html" %}
{% block header %}
<div class="container"><center><h3>Все статьи пользователя {{blogentry.blogentryowner}}</h3></center>
</div>
{% endblock header %}

{% block content %}
{% load static %}

<div class="container-float">
    <div class="row">
        <div class="col" style="width: 500px">
            <br><br>
          
        </div>
        <div class="col">
            
{%for blogentry in alluserentries%}
<div class="panel panel-default" style="width: 570px">
    <div class="panel-heading" style="width: 568px">
      <center><a href="{% url 'blog:blogentry' blogentry.id %}"><img src="{{blogentry.blogentryimage.url}}" width='540px'></a></center>

    </div>
    <div class="panel-body" style="width: 480px">
        <a href="{% url 'blog:blogentry' blogentry.id %}"> "{{blogentry.blogtitle}}"</a><br>
        {{ blogentry.blogtext }}<small><a href="{% url 'blog:blogentry' blogentry.id %}">{{ read_more }}</a></small>                    
        <br>

        <small>Континент - {{blogentry.blogtopic}},
        тип отдыха - {{blogentry.blogresttypes}}
        </small>
        <h5><small>
            Добавлено пользователем
            <a href="{% url 'blog:alluserentries' blogentry.blogentryowner.id %}">{{blogentry.blogentryowner}} </a>
            в {{ blogentry.blogdate_added|date:'d.m.Y в H:i' }}
        </small></h5>
        {% if user == blogentry.blogentryowner %}
        <small>
            <a href="{% url 'blog:edit_blogentry' blogentry.id %}">Редактировать статью</a>
        </small>
        <small>
            | <a href="{% url 'blog:delete_blogentry' blogtopic.id blogentry.id %}">Удалить статью</a>
        </small>
        {%endif%}
    </div>

</div>

{% endfor %}
</div>
<div class="col" style="width: 500px">
<br><br>
<center><img src="{% static 'images/ad.gif'%}" alt="" width="250"></center>
<br>

<center><img src="{% static 'images/ad2.gif'%}" alt="" width="250"></center>
</div>

{% endblock content %}

blog/templates/blog/blogentry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}
{% load static %}
{% block header %}
<style>
  .center-img {
    display: block;
    margin: 0 auto;
    height: 300px;
  }


</style>
<h2>{{ blogentry.blogtitle }}</h2>
<p>
    <small>
        <a href="{% url 'blog:blog' %}">Вернуться ко всем статьям блога</a>
    </small>
</p>
{% endblock header %}

{% block content %}

<div class="panel panel-default">
    <div class="panel-heading">
        <h5>
            Опубликовано {{ blogentry.blogdate_added|date:'d.m.Y в H:i' }}
        </h5>
    </div>
    <div class="panel-body">
        <img src="{{ blogentry.blogentryimage.url }}" alt='' class='center-img'>
        {{ blogentry.blogtext|linebreaks }}
    </div>
    <div class="panel-body">
        {% if user == blogentry.blogentryowner %}
        <small>
            <a href="{% url 'blog:edit_blogentry' blogentry.id %}">Редактировать статью</a>
        </small>
        <small>
            | <a href="{% url 'blog:delete_blogentry' blogtopic.id blogentry.id %}">Удалить статью</a>
        </small>
        {%endif%}
        <br>

        <small>Поделиться этой статьёй в соцсетях:</small>
        <a href="http://vk.com/share.php?url=https://Gwin_project.by/blogentry/{{ blogentry.id }}"
           target="_blank" rel="nofollow">
            <img src="{% static 'sn/vk.jpg'  %}" width='20px'>
        </a>
        <a href="https://twitter.com/intent/tweet?text=https://Gwin_project.by/blogentry/{{ blogentry.id }}"
           target="_blank" rel="nofollow">
            <img src="{% static 'sn/twitter.png'  %}" width='20px'>
        </a>
        <a href="https://www.facebook.com/sharer/sharer.php?u=https://Gwin_project.by/blogentry/{{ blogentry.id }}"
           target="_blank" rel="nofollow">
            <img src="{% static 'sn/facebook.png'  %}" width='20px'>
        </a>
        <a href="https://connect.ok.ru/offer?url=https://Gwin_project.by/blogentry/{{ blogentry.id }}"
           target="_blank" rel="nofollow">
            <img src="{% static 'sn/ok.png'  %}" width='20px'>
        </a>
        <p></p>
        <p>
            <small>
                <a href="{% url 'blog:blog' %}">Вернуться ко всем статьям блога</a>
            </small>
        </p>
    </div>
    <div class="panel-body">
        <p>Оставить комментарий:</p>
        <form method="post" action="{% url 'blog:blogentry' blogentry.id %}" class="form">
            {% csrf_token %}
            {% bootstrap_form form %}

            {% buttons %}
            <button name="submit" class="btn btn-primary">Добавить комментарий</button>
            {% endbuttons %}
            <input type="hidden" name="next" value="{% url 'blog:blogentry' blogentry.id %}"/>
        </form>
    </div>
</div>

<div class="panel-body">
    <p> Комментарии к статье: </p>
    {% for blogcomment in all_comments %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h5>
                Комментарий от пользователя {{ blogcomment.blogname }}
                <p><small>Комментарий создан {{blogcomment.blogcreated | date:'d.m.Y в H:i'}}<br>
                    {% if blogcomment.blogcreated != blogcomment.blogupdated %}
                    Комментарий обновлён {{blogcomment.blogupdated | date:'d.m.Y в H:i'}}
                    {% endif %}
                </small></p>

            </h5>
        </div>
        <div class="panel-body">
            <p>
                {{ blogcomment.blogbody }}
            </p>
            {% if blogcomment.blogname == request.user %}
            <h5><p><small>
                <a href="{% url 'blog:edit_blogcomment' blogentry.id blogcomment.id  %}">Редактировать комментарий</a>
            </small></p></h5>
            {% else %}
            <p></p>
            {% endif %}
        </div>
    </div>
    {% empty %}
    К этой статье пока не было оставлено никаких комментариев...Станьте первым!
    {% endfor %}
</div>
<div class="panel-body">
    <p>
        <a href="{% url 'blog:blogentry' blogentry.id %}">Вернуться к началу статьи "{{ blogentry }}"</a>
    </p>
    <p>
        <a href="{% url 'blog:blog' %}">Вернуться ко всем статьям блога</a>
    </p>
</div>
{% endblock content %}

blog/templates/blog/blogindex.html
{% extends 'learning_logs/base.html' %}
{% block header %}

{% endblock header %}

{% block content %}
{% load static %}
<p>
    <center><a href="{% url 'blog:new_blogentry' blogtopic.id %}">Добавить новую статью</a></center>
</p>


<div class="container-float">
    <div class="row">
        <div class="col" style="width: 500px">
            <br><br>
          
        </div>
        <div class="col">
            <h4>Это блог наших читателей. Делитесь своими эмоциями с другими!</h4>
            {%for blogentry in blogtop%}
            <div class="panel panel-default" style="width: 570px">
                <div class="panel-heading" style="width: 568px">
                  <center><a href="{% url 'blog:blogentry' blogentry.id %}"><img src="{{blogentry.blogentryimage.url}}" width='540px'></a></center>

                </div>
                <div class="panel-body" style="width: 480px">
                    <a href="{% url 'blog:blogentry' blogentry.id %}"> "{{blogentry.blogtitle}}"</a><br>
                    {{ blogentry.blogtext }}<small><a href="{% url 'blog:blogentry' blogentry.id %}">{{ read_more }}</a></small>                    
                    <br>

                    <small>Континент - {{blogentry.blogtopic}},
                    тип отдыха - {{blogentry.blogresttypes}}
                    </small>
                    <h5><small>
                        Добавлено пользователем
                        <a href="{% url 'blog:alluserentries' blogentry.blogentryowner.id %}">{{blogentry.blogentryowner}} </a>
                        в {{ blogentry.blogdate_added|date:'d.m.Y в H:i' }}
                    </small></h5>
                    {% if user == blogentry.blogentryowner %}
                    <small>
                        <a href="{% url 'blog:edit_blogentry' blogentry.id %}">Редактировать статью</a>
                    </small>
                    <small>
                        | <a href="{% url 'blog:delete_blogentry' blogtopic.id blogentry.id %}">Удалить статью</a>
                    </small>
                    {%endif%}
                </div>

            </div>
 
            {% empty %}
            Упс! По данной теме ещё нет ни одной статьи... Станьте первым, жмите на ссылку
            "Добавить новую статью"!
            {% endfor %}
        </div>
        <div class="col" style="width: 500px">
            <br><br>
            <center><img src="{% static 'images/ad.gif'%}" alt="" width="250"></center>
            <br>
  
            <center><img src="{% static 'images/ad2.gif'%}" alt="" width="250"></center>
        </div>

    </div>

    {% endblock content %}

blog/templates/blog/blogtopic.html
{% extends 'learning_logs/base.html' %}
{% block header %}
<h2>{{ blogtopic }}</h2>
{% endblock header %}

{% block content %}
<p>
    <a href="{% url 'blog:new_blogentry' blogtopic.id %}">Добавить новую статью</a>
</p>
{% for blogentry in blogentries %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h5>
            <a href="{% url 'blog:blogentry' blogentry.id %}"> {{blogentry.blogtitle}}</a>
        </h5>
    </div>
    <div class="panel-body">
        {{ blogentry.blogtext }}
        <small>
            <a href="{% url 'blog:blogentry' blogentry.id %}">{{ read_more }}</a>
        </small>
        <p>
        <h5><small>
            Добавлено пользователем
            <a href="{% url 'blog:alluserentries' blogentry.blogentryowner.id %}">{{blogentry.blogentryowner}} </a>
            в {{ blogentry.blogdate_added|date:'d.m.Y в H:i' }}
        </small></h5>
        </p>
        {% if user == blogentry.blogentryowner %}
        <small>
            <a href="{% url 'blog:edit_blogentry' blogentry.id %}">Редактировать статью</a>
        </small>
        <small>
            | <a href="{% url 'blog:delete_blogentry' blogtopic.id blogentry.id %}">Удалить статью</a>
        </small>
        {%endif%}
    </div>
</div>
{% empty %}
Упс! По данной теме ещё нет ни одной статьи... Станьте первым, жмите на ссылку
"Добавить новую статью"!
{% endfor %}
{% endblock content %}

blog/templates/blog/edit_blogcomment.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
<h4>Редактировать комментарий: </h4>
{% endblock header %}

{% block content %}
<form method="post" action="{% url 'blog:edit_blogcomment' blogentry.id blogcomment.id %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-primary">Редактировать комментарий</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'blog:blogentry' blogentry.id  %}"/>
</form>
{% endblock content %}

blog/templates/blog/edit_blogentry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
<h4>Редактировать статью</h4>
{% endblock header %}

{% block content %}
<form method="post" action="{% url 'blog:edit_blogentry' blogentry.id %}" class="form" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-primary">Редактировать статью</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'blog:blogtopic' blogtopic.id %}"/>
</form>
{% endblock content %}

blog/templates/blog/myentries.html
{% extends "learning_logs/base.html" %}
{% block header %}
<div class="container"><center><h3>Все твои статьи:</h3></center>
</div>
{% endblock header %}

{% block content %}
{% load static %}

<div class="container-float">
    <div class="row">
        <div class="col" style="width: 500px">
            <br><br>
          
        </div>
        <div class="col">
            
{%for blogentry in myentries%}
<div class="panel panel-default" style="width: 570px">
    <div class="panel-heading" style="width: 568px">
      <center><a href="{% url 'blog:blogentry' blogentry.id %}"><img src="{{blogentry.blogentryimage.url}}" width='540px'></a></center>

    </div>
    <div class="panel-body" style="width: 480px">
        <a href="{% url 'blog:blogentry' blogentry.id %}"> "{{blogentry.blogtitle}}"</a><br>
        {{ blogentry.blogtext }}<small><a href="{% url 'blog:blogentry' blogentry.id %}">{{ read_more }}</a></small>                    
        <br>

        <small>Континент - {{blogentry.blogtopic}},
        тип отдыха - {{blogentry.blogresttypes}}
        </small>
        <h5><small>
            Добавлено пользователем
            <a href="{% url 'blog:alluserentries' blogentry.blogentryowner.id %}">{{blogentry.blogentryowner}} </a>
            в {{ blogentry.blogdate_added|date:'d.m.Y в H:i' }}
        </small></h5>
        {% if user == blogentry.blogentryowner %}
        <small>
            <a href="{% url 'blog:edit_blogentry' blogentry.id %}">Редактировать статью</a>
        </small>
        <small>
            | <a href="{% url 'blog:delete_blogentry' blogtopic.id blogentry.id %}">Удалить статью</a>
        </small>
        {%endif%}
    </div>

</div>
{% empty %}
Ты ещё ничего не написал в блог? Самое время <a href="{% url 'blog:new_blogentry' 1 %}">начать</a>!
{% endfor %}
</div>
<div class="col" style="width: 500px">
<br><br>
<center><img src="{% static 'images/ad.gif'%}" alt="" width="250"></center>
<br>

<center><img src="{% static 'images/ad2.gif'%}" alt="" width="250"></center>
</div>

{% endblock content %}

blog/templates/blog/new_blogentry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
<h4>Добавить в блог новую статью</h4>
{% endblock header %}

{% block content %}
<form method="post" action="{% url 'blog:new_blogentry' blogtopic.id %}" class="form" enctype="multipart/form-data">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-primary">Добавить статью</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'blog:blogtopic' blogtopic.id %}"/>
</form>
{% endblock content %}