blog/urls.py
from . import views
from django.conf.urls import url

app_name = "blog"

urlpatterns = [
    url(r'^$', views.blog, name='blog'),
    url(r'^blogtopics/$', views.blogtopics, name='blogtopics'),
    url(r'^blogtopics/(?P<blogtopic_id>\d+)/$', views.blogtopic, name='blogtopic'),
    url(r'^new_blogentry/(?P<blogtopic_id>\d+)/$', views.new_blogentry, name='new_blogentry'),
    url(r'^edit_blogentry/(?P<blogentry_id>\d+)/$', views.edit_blogentry, name='edit_blogentry'),
    url(r'^blogentry/(?P<blogentry_id>\d+)/$', views.blogentry, name='blogentry'),
    url(r'^blogentry/(?P<blogentry_id>\d+)/add_to_fav/$', views.add_to_fav, name='add_to_fav'),
    url(r'^blogentry/(?P<blogentry_id>\d+)/remove_from_fav/$', views.remove_from_fav, name='remove_from_fav'),
    url(r'edit_blogcomment/(?P<blogentry_id>\d+)/(?P<blogcomment_id>\d+)/$', views.edit_blogcomment,
        name='edit_blogcomment'),
    url(r'^blogfavourites/$', views.blogfavourites, name='blogfavourites'),
    url(r'^delete_blogentry/(?P<blogtopic_id>\d+)/(?P<blogentry_id>\d+)/$', views.delete_blogentry,
        name='delete_blogentry'),
    url(r'^alluserentries/(?P<user_id>\d+)/$', views.alluserentries, name='alluserentries'),
    url(r'^myentries/(?P<user_id>\d+)/$', views.myentries, name='myentries'),
]

learning_log/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include('learning_logs.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^notes/', include('notes.urls', namespace='notes')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/urls.py
from . import views
from django.urls import path
from django.conf.urls import url

app_name = "notes"

urlpatterns = [
    url(r'^$', views.notes, name='notes'),
    url(r'^(?P<note_id>\d+)/$', views.note, name='note'),
    url(r'^new_note/$', views.new_note, name='new_note'),
    url(r'^edit_note/(?P<note_id>\d+)/$', views.edit_note, name='edit_note'),
    url(r'^delete_note/(?P<note_id>\d+)/$', views.delete_note, name='delete_note'),

    # url(r'^entry/(?P<entry_id>\d+)/$', views.entry, name='entry'),
    # url(r'^entry/(?P<entry_id>\d+)/add_to_fav/$', views.add_to_fav, name='add_to_fav'),
    # url(r'^entry/(?P<entry_id>\d+)/remove_from_fav/$', views.remove_from_fav, name='remove_from_fav'),
    # url(r'^favourites/$', views.favourites, name='favourites'),
    # url(r'edit_comment/(?P<entry_id>\d+)/(?P<comment_id>\d+)/$', views.edit_comment, name='edit_comment'),

]

notes/models.py
from django.db import models
from django.contrib.auth.models import User


# создание модели заметки Notesentry с указанием названия заметки, текста заметки, даты добавления заметки,
# автора заметки
class Notesentry(models.Model):
    notestitle = models.CharField(max_length=50)
    notestext = models.TextField()
    notesdate_added = models.DateTimeField(auto_now_add=True)
    notesowner = models.ForeignKey(User, on_delete=models.CASCADE)

    # возвращает представление текста как 'текст'+'...', если длина заметки составляет более 50 знаков
    def __str__(self):
        if len(self.notestext) > 50:
            return self.notestext[:50] + '...'
        else:
            return self.notestext

notes/forms.py
from django import forms
from .models import Notesentry


# форма для модели Notesentry с указанием полей и их обозначениями
class NotesentryForm(forms.ModelForm):
    class Meta:
        model = Notesentry
        fields = ['notestitle', 'notestext']
        labels = {'notestitle': 'Название', 'notestext': 'Заметка'}
        widgets = {'notestext': forms.Textarea(attrs={'cols': 80})}

notes/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Notesentry
from .forms import NotesentryForm


# функция представления всех заметок на странице
@login_required
def notes(request):
    notes = Notesentry.objects.filter(notesowner=request.user).order_by('-notesdate_added')
    read_more = '...продолжить читать заметку'
    for note in notes:
        if note.notesowner != request.user:
            return render(request, 'learning_logs/notyours.html')
        if len(note.notestext) > 50:
            note.notestext = note.notestext[:50]

    context = {'notes': notes, 'read_more': read_more}
    return render(request, 'notes/notes.html', context)


# функция представления заметки
@login_required
def note(request, note_id):
    note = Notesentry.objects.get(id=note_id)
    if note.notesowner != request.user:
        return render(request, 'learning_logs/notyours.html')
    context = {'note': note}
    return render(request, 'notes/note.html', context)


# функция добавления новой заметки
@login_required
def new_note(request):
    if request.method != 'POST':
        form = NotesentryForm()
    else:
        form = NotesentryForm(request.POST)
        if form.is_valid():
            new_note = form.save(commit=False)
            new_note.notesowner = request.user
            new_note.save()
            return HttpResponseRedirect(reverse('notes:notes'))
    context = {'form': form}
    return render(request, 'notes/new_note.html', context)


# функция изменения заметки
@login_required
def edit_note(request, note_id):
    note = Notesentry.objects.get(id=note_id)
    if note.notesowner != request.user:
        return render(request, 'learning_logs/notyours.html')
    if request.method != 'POST':
        form = NotesentryForm(instance=note)
    else:
        form = NotesentryForm(instance=note, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('notes:note', args=[note.id]))
    context = {'note': note, 'form': form}
    return render(request, 'notes/edit_note.html', context)

# функция удаления заметки
@login_required
def delete_note(request, note_id):
    note = Notesentry.objects.get(id=note_id)
    if note.notesowner != request.user:
        return render(request, 'learning_logs/notyours.html')
    else:
        note = Notesentry.objects.filter(id=note_id)
        note.delete()
    return HttpResponseRedirect(reverse('notes:notes'))

notes/templates/notes/edit_note.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
<h4>Редактировать заметку:</h4>
{% endblock header %}

{% block content %}
<form method="post" action="{% url 'notes:edit_note' note.id %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-primary">Редактировать заметку</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'notes:note' note.id %}"/>
</form>
{% endblock content %}

notes/templates/notes/new_note.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}
{% block header %}
<h4>Добавить новую заметку</h4>
{% endblock header %}

{% block content %}
<form method="post" action="{% url 'notes:new_note' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-primary">Добавить заметку</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{% url 'notes:notes' %}"/>
</form>
{% endblock content %}

notes/templates/notes/note.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}
{% load static %}
{% block header %}
<h2>{{ note.notestitle }}</h2>
{% endblock header %}

{% block content %}

<div class="panel panel-default">
    <div class="panel-heading">
        <h5>
            Опубликовано {{ note.notesdate_added|date:'d.m.Y в H:i' }}
        </h5>
    </div>
    <div class="panel-body">
        {{ note.notestext|linebreaks }}
    </div>
    <div class="panel-body">
        <small>
            <a href="{% url 'notes:edit_note' note.id %}">Редактировать заметку</a>
        </small>
        <small>
            | <a href="{% url 'notes:delete_note' note.id %}">Удалить заметку</a>
        </small>
    </div>
    <div class="panel-body">
        <p>
            <small>
                <a href="{% url 'notes:note' note.id %}">Вернуться к началу заметки</a>
            </small>
            <br>
            <small>
                <a href="{% url 'notes:notes' %}">Вернуться ко всем моим заметкам</a>
            </small>
        </p>
    </div>
</div>
{% endblock content %}

notes/templates/notes/notes.html
{% extends 'learning_logs/base.html' %}
{% block header %}
<h2>Мои заметки</h2>
{% endblock header %}

{% block content %}
<p>
    <a href="{% url 'notes:new_note' %}">Добавить новую заметку</a>
</p>
{% for note in notes %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h5>
            <a href="{% url 'notes:note' note.id %}"> {{note.notestitle}}</a>
        </h5>
    </div>
    <div class="panel-body">
        {{ note.notestext }}
        <small>
            <a href="{% url 'notes:note' note.id %}">{{ read_more }}</a>
        </small>
        <p>
            <small>
                Опубликовано {{ note.notesdate_added|date:'d.m.Y в H:i' }}
            </small>
        </p>
        <small>
            <a href="{% url 'notes:edit_note' note.id %}">Редактировать заметку</a>
        </small>
        <small>
            | <a href="{% url 'notes:delete_note' note.id %}">Удалить заметку</a>
        </small>
    </div>
</div>
{% empty %}
Упс! Вы пока ещё не добавили ни одной заметки... Начинайте, жмите на ссылку
"Добавить новую заметку"!
{% endfor %}
{% endblock content %}